# version: "3.8"
# References: https://www.emqx.io/docs/en/latest/deploy/install-docker.html
services:
  device-service-1:
    image: we-learning/device-service:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.DeviceService/Dockerfile
    restart: unless-stopped
    ports:
      - 5294:80
    environment:
      Logging__LogLevel__Default: Debug
      AppSettings__DevicesPerInterval: 200
      AppSettings__SimulatorInterval: 1000
      AppSettings__LatencyMs: 500
    networks:
      - we-bridge

  fb-worker-1:
    image: we-learning/fb-worker:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.FBWorker/Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 3.0
          memory: 750M
      replicas: 1
    environment:
      Logging__LogLevel__Default: Debug
      FunctionBlock__Timeout: 00:30:00
      FunctionBlock__JavascriptEngine__LibraryFolderPath: /app/libs
      AppSettings__WorkerCount: 1
      AppSettings__InitialConcurrencyLimit: 0
      AppSettings__ScaleFactor: 50
      AppSettings__ScaleCheckInterval: 5000
      AppSettings__AcceptedAvailableConcurrency: 0.3
      AppSettings__IdealUsage: 0.75
      AppSettings__DeviceServiceUrl: http://device-service-1
      TaskLimiter__InitialLimit: 0
      TaskLimiter__AvailableCores: 3
      TaskLimiter__TargetCpuUtil: 0.75
      TaskLimiter__WaitTime: 4000
      TaskLimiter__ServiceTime: 10
    networks:
      - we-bridge

networks:
  we-bridge:
    driver: bridge
