# version: "3.8"
# References: https://www.emqx.io/docs/en/latest/deploy/install-docker.html
services:
  device-service-1:
    image: we-learning/device-service:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.DeviceService/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      Logging__LogLevel__Default: Debug
      AppSettings__DevicesPerInterval: 200
      AppSettings__SimulatorInterval: 1000
      AppSettings__LatencyMs: 500
      ProducerConfig__BootstrapServers: kafka-1:19092
      AdminClientConfig__BootstrapServers: kafka-1:19092
    networks:
      - we-bridge
    depends_on:
      - kafka-1

  fb-worker-1:
    image: we-learning/fb-worker:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.FBWorker/Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 3.0
          memory: 750M
      replicas: 1
    environment:
      Logging__LogLevel__Default: Debug
      FunctionBlock__Timeout: 00:30:00
      FunctionBlock__JavascriptEngine__LibraryFolderPath: /app/libs
      AppSettings__WorkerCount: 1
      AppSettings__InitialConcurrencyLimit: 0
      AppSettings__ScaleFactor: 50
      AppSettings__ScaleCheckInterval: 5000
      AppSettings__AcceptedAvailableConcurrency: 0.3
      AppSettings__IdealUsage: 0.75
      AppSettings__DeviceServiceUrl: http://device-service-1
      TaskLimiter__InitialLimit: 0
      TaskLimiter__AvailableCores: 3
      TaskLimiter__TargetCpuUtil: 0.75
      TaskLimiter__WaitTime: 4000
      TaskLimiter__ServiceTime: 10
      ConsumerConfig__BootstrapServers: kafka-1:19092
    networks:
      - we-bridge
    depends_on:
      - kafka-1

  kafka-1:
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,PLAINTEXT://kafka-1:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,EXTERNAL://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    networks:
      - we-bridge

networks:
  we-bridge:
    driver: bridge
