services:
  device-service-1:
    image: we-learning/device-service:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.DeviceService/Dockerfile
    ports:
      - 5294:80
    deploy:
      resources:
        limits:
          cpus: 3.0
          memory: 500M
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      Logging__LogLevel__Default: Debug
      AppSettings__DevicesPerInterval: 200
      AppSettings__SimulatorInterval: 1000
      AppSettings__LatencyMs: 75
      RabbitMqClient__HostName: rabbitmq-1
    networks:
      - we-bridge
    depends_on:
      rabbitmq-1:
        condition: service_healthy

  fb-worker-1:
    image: we-learning/fb-worker:latest
    build:
      context: .
      dockerfile: Samples/WELearning.Samples.FBWorker/Dockerfile
    deploy:
      resources:
        limits:
          cpus: 1.5
          memory: 500M
      replicas: 1
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      Logging__LogLevel__Default: Debug
      FunctionBlock__Timeout: 00:30:00
      FunctionBlock__JavascriptEngine__LibraryFolderPath: /app/libs
      AppSettings__WorkerCount: 1
      AppSettings__DeviceServiceUrl: http://device-service-1
      TaskLimiter__InitialLimit: 0
      TaskLimiter__AvailableCores: 3
      TaskLimiter__TargetCpuUtil: 0.75
      TaskLimiter__WaitTime: 4000
      TaskLimiter__ServiceTime: 5
      RateScaling__InitialLimit: 0
      RateScaling__ScaleFactor: 30
      RateScaling__ScaleCheckInterval: 5000
      RateScaling__AcceptedAvailableCount: 0.3
      RateScaling__AcceptedQueueCount: 5
      RateScaling__IdealUsage: 0.75
      RabbitMqClient__HostName: rabbitmq-1
      RabbitMqChannel__PrefetchCount: 5000
    networks:
      - we-bridge
    depends_on:
      rabbitmq-1:
        condition: service_healthy

  rabbitmq-1:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./deployment/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./deployment/rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - we-bridge
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "2G"

networks:
  we-bridge:
    driver: bridge
