services:
  redis-1:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./deployment/redis/redis.conf:/data/redis.conf
    command: ["redis-server", "/data/redis.conf"]

networks:
  we-learning:
    driver: bridge
