name: PR Check

on:

  pull_request:
    branches: [ main, release/2.x, 3.x ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test
      run: dotnet test --configuration Release --logger GitHubActions

  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test
      run: dotnet test --configuration Release --logger GitHubActions

  macos:
    runs-on: macos-14

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test
      run: dotnet test --configuration Release --logger GitHubActions
